### ISSUE TITLE
I/O Error with Example Web Docker

### ISSUE THREAD

**Issue by ATM-Tech** [jpdillingham/Soulseek.NET#315]
Hello, I was trying to set up the example web docker with the full set of provided options, including my own paths. When I try to run the docker, I get an I/O error. Just figured that you would probably want to know.
```
Unhandled Exception: System.IO.IOException: Input/output error
at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
at System.IO.FileSystemWatcher.StartRaisingEvents()
at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0()
at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at WebAPI.Program.Main(String[] args) in /home/jp/source/repos/Soulseek.NET/examples/Web/api/Program.cs:line 12
```

**Comment by jpdillingham** [comment]
Thanks for reporting this.  Can you share more about your setup, particularly base OS?  I'd like to see if I can reproduce it.

This appears to be boilerplate ASP.NET configuration trying to set up a hot reload for the config.  It isn't used, so I'll work on disabling it.

**Comment by atm0915** [comment]
I am running Unraid which I believe is based off of Slackware. Possibly an issue of the combined filesystem?

**Comment by jpdillingham** [comment]
I just pushed a new build of the image with the change from #316, please let me know if that changes anything.

**Comment by ATM-Tech** [comment]
I just tried it again and I got the same error as before.

**Comment by jpdillingham** [comment]
It sounds like the app doesn't have sufficient rights to read files in the `/app` directory, but I'm having a hard time understanding why.

Can you share more about your Unraid configuration? I'd like to see if I can reproduce it on my end.

**Comment by ATM-Tech** [comment]
In terms of hardware, I'm running an i7-4470k (4C/8T) with 32GB of DDR3. I've got four 2TB hard drives for the array (one being a parity drive) and a 512GB NVME SSD as my cache drive. My configuration for the docker is as follows: [https://i.imgur.com/ULwezYo.png](https://i.imgur.com/ULwezYo.png). That is all the relevant information I can think of. Interestingly, if I add a path to the /app folder in the container (-v /mnt/user/appdata/slsk-web-example:/app), I get a new error:
 ```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by jpdillingham** [comment]
@ATM-Tech sorry I never followed up on this; things changed so much that I doubt the issue is still relevant.  Please have a look at [slskd](https://github.com/slskd/slskd) and see if you experience the same issues.
