### ISSUE TITLE
Fix error "Unable to configure HTTPS endpoint" #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [jpdillingham/Soulseek.NET#392]
Hi!

Hope you're well

Sorry for brevity

Updated my docker container today and get this error:

```
Serving static content from /app/wwwroot

Connected and logged in.

Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.

For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.

at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)

at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)

at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)

at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)

at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)

at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)

at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)

at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)

at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)

at WebAPI.Program.Main(String[] args) in /home/jp/source/repos/Soulseek.NET/examples/Web/api/Program.cs:line 13
```

Help?

Hope to hear back

Sincerely

**Comment by bruuteuzius** [comment]
Are you running your docker container from a place that serves https? Because I also got this message and my synology NAS runs https. Thought that might be the problem.

**Comment by ldexterldesign** [comment]
Hi @bruuteuzius,

Thanks for reply

Hosted locally on my Mac/Docker http://0.0.0.0:5000

I could be wrong but I imagine this is something related to..?:
https://github.com/jpdillingham/Soulseek.NET/issues/364
https://github.com/jpdillingham/Soulseek.NET/issues/366

Sincerely

**Comment by bruuteuzius** [comment]
Then we both have to figure this out locally 😉I forked the repo and I'm trying to debug this but having trouble setting up configuration.

**Comment by ldexterldesign** [comment]
I’m afraid it’s not something I can fix. I don’t have any ASP.NET knowledge and it’s not on my radar to invest time in ATM.

But I wish you luck!

Happy to help otherwise

Sincerely

**Comment by jpdillingham** [comment]
Apologies for this; I was playing around with SSL a while back and *thought* I rolled this change back.  I just published a new Docker image which shouldn't be attempting to serve HTTPS.  I'll be more careful about what I push out with the `latest` tag in the future.

Let me know if this is still a problem.

**Comment by bruuteuzius** [comment]
@jpdillingham  thanx! I redownloaded the docker image and it worked like a charm :+1:  
I tried debugging it locally in vscode but I didn't setup configuration well. Do you have an example so I can perhaps debug and help?

**Comment by ldexterldesign** [comment]
Hey @jpdillingham,

Grabbed the new image and I'm seeking souls again

Thanks!

PS and there's even a search enter shortcut in this version 💞
