### ISSUE TITLE
Refactor test 'DownloadToFileAsync uses size from TransferResponse given null size when queued'

### ISSUE THREAD

**Issue by jpdillingham** [jpdillingham/Soulseek.NET#756]
https://app.circleci.com/pipelines/github/jpdillingham/Soulseek.NET/2804/workflows/edd5c1ce-54a7-4e8a-aba7-2893bdd492ff/jobs/2946

**Comment by jpdillingham** [comment]
I'm seeing a common theme to a few of these failures:

```
IConnection.Disconnect(null, System.IO.IOException: The process cannot access the file '/root/project/tests/Soulseek.Tests.Unit/bin/Release/net6.0/local' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Soulseek.IOAdapter.GetFileStream(String path, FileMode mode, FileAccess access, FileShare share) in /_/src/Common/IOAdapter.cs:line 45
   at Soulseek.SoulseekClient.<>c__DisplayClass333_0.<DownloadToFileAsync>b__0() in /_/src/SoulseekClient.cs:line 3050
   at Soulseek.SoulseekClient.DownloadToStreamAsync(String username, String remoteFilename, Func`1 outputStreamFactory, Nullable`1 size, Int64 startOffset, Int32 token, TransferOptions options, CancellationToken cancellationToken) in /_/src/SoulseekClient.cs:line 3227)
```

I've taken a look at these flakes before and concluded that there's no timing involved and not really a reason they should flake.  It seems there's an IO issue that's killing the connection early and preventing the rest of the test from running, which fails mock invocations.
